"""empty message

Revision ID: 151a98eb9121
Revises: 6df46c004e4d
Create Date: 2020-09-12 22:43:23.007000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "151a98eb9121"
down_revision = "6df46c004e4d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_information",
        sa.Column(
            "type", sa.Boolean(), nullable=True, comment="用户类型 True管理员 False普通用户"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_information", "type")
    # ### end Alembic commands ###
