"""empty message

Revision ID: 1e7e7cd24cb5
Revises: 151a98eb9121
Create Date: 2020-10-14 15:31:23.154134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7e7cd24cb5'
down_revision = '151a98eb9121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('get_time', sa.String(length=2000), nullable=True),
    sa.Column('ip', sa.String(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='代理池',
    mysql_charset='utf8'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pool')
    # ### end Alembic commands ###
