"""empty message

Revision ID: 1f95e838691d
Revises: 2e283a193a4c
Create Date: 2020-09-09 00:50:22.061664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f95e838691d'
down_revision = '2e283a193a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_information',
    sa.Column('id', sa.String(length=50), nullable=False, comment='用户唯一标识符'),
    sa.Column('userName', sa.String(length=2000), nullable=False, comment='用户名'),
    sa.Column('name', sa.String(length=2000), nullable=True, comment='用户姓名'),
    sa.Column('birthDate', sa.String(length=2000), nullable=True, comment='出生日期'),
    sa.Column('telephone', sa.String(length=2000), nullable=True, comment='电话号码'),
    sa.Column('email', sa.String(length=2000), nullable=True, comment='Email'),
    sa.Column('passwordHash', sa.String(length=2000), nullable=True, comment='密码哈希值（不直接保存明文密码）'),
    sa.Column('status', sa.String(length=2000), nullable=True, comment='用户状态 1、激活 2、未激活 3、禁用'),
    sa.Column('remark', sa.String(length=2000), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户基本信息表',
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_user_information_id'), 'user_information', ['id'], unique=False)
    op.drop_index('ix_user_id', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.VARCHAR(length=50), nullable=False, comment='用户唯一标识符'),
    sa.Column('userName', mysql.VARCHAR(length=2000), nullable=False, comment='用户名'),
    sa.Column('name', mysql.VARCHAR(length=2000), nullable=True, comment='用户姓名'),
    sa.Column('birthDate', mysql.VARCHAR(length=2000), nullable=True, comment='出生日期'),
    sa.Column('telephone', mysql.VARCHAR(length=2000), nullable=True, comment='电话号码'),
    sa.Column('email', mysql.VARCHAR(length=2000), nullable=True, comment='Email'),
    sa.Column('passwordHash', mysql.VARCHAR(length=2000), nullable=True, comment='密码哈希值（不直接保存明文密码）'),
    sa.Column('status', mysql.VARCHAR(length=2000), nullable=True, comment='用户状态 1、激活 2、未激活 3、禁用'),
    sa.Column('remark', mysql.VARCHAR(length=2000), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户基本信息表',
    mysql_comment='用户基本信息表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.drop_index(op.f('ix_user_information_id'), table_name='user_information')
    op.drop_table('user_information')
    # ### end Alembic commands ###
