"""empty message

Revision ID: 25b1d9084dd4
Revises: 
Create Date: 2020-12-03 14:46:41.719675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b1d9084dd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('get_time', sa.String(length=2000), nullable=True),
    sa.Column('ip', sa.String(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='代理池',
    mysql_charset='utf8'
    )
    op.create_table('user_information',
    sa.Column('id', sa.String(length=50), nullable=False, comment='用户唯一标识符'),
    sa.Column('userName', sa.String(length=2000), nullable=False, comment='用户名'),
    sa.Column('name', sa.String(length=2000), nullable=True, comment='用户姓名'),
    sa.Column('birthDate', sa.String(length=2000), nullable=True, comment='出生日期'),
    sa.Column('telephone', sa.String(length=2000), nullable=True, comment='电话号码'),
    sa.Column('email', sa.String(length=2000), nullable=True, comment='Email'),
    sa.Column('passwordHash', sa.String(length=2000), nullable=True, comment='密码哈希值（不直接保存明文密码）'),
    sa.Column('status', sa.String(length=2000), nullable=True, comment='用户状态 0000激活 0001未激活 0010禁用'),
    sa.Column('type', sa.Boolean(), nullable=True, comment='用户类型 True管理员 False普通用户'),
    sa.Column('remark', sa.String(length=2000), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户基本信息表',
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_user_information_id'), 'user_information', ['id'], unique=False)
    op.create_table('user_commodity',
    sa.Column('commodityID', sa.String(length=50), nullable=False, comment='商品唯一标识符'),
    sa.Column('userID', sa.String(length=50), nullable=True, comment='用户唯一标识符'),
    sa.Column('commodityName', sa.String(length=2000), nullable=True, comment='商品名称'),
    sa.Column('hopePrice', sa.String(length=2000), nullable=True, comment='期望价格'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='商品状态 0000有效 0001无效 0010中止 0011删除'),
    sa.Column('remark', sa.String(length=2000), nullable=True, comment='备注'),
    sa.ForeignKeyConstraint(['userID'], ['user_information.id'], ),
    sa.PrimaryKeyConstraint('commodityID'),
    comment='用户商品表',
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_user_commodity_commodityID'), 'user_commodity', ['commodityID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_commodity_commodityID'), table_name='user_commodity')
    op.drop_table('user_commodity')
    op.drop_index(op.f('ix_user_information_id'), table_name='user_information')
    op.drop_table('user_information')
    op.drop_table('pool')
    # ### end Alembic commands ###
