"""empty message

Revision ID: 2e283a193a4c
Revises: 
Create Date: 2020-09-09 00:46:55.410779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e283a193a4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=50), nullable=False, comment='用户唯一标识符'),
    sa.Column('userName', sa.String(length=2000), nullable=False, comment='用户名'),
    sa.Column('name', sa.String(length=2000), nullable=True, comment='用户姓名'),
    sa.Column('birthDate', sa.String(length=2000), nullable=True, comment='出生日期'),
    sa.Column('telephone', sa.String(length=2000), nullable=True, comment='电话号码'),
    sa.Column('email', sa.String(length=2000), nullable=True, comment='Email'),
    sa.Column('passwordHash', sa.String(length=2000), nullable=True, comment='密码哈希值（不直接保存明文密码）'),
    sa.Column('status', sa.String(length=2000), nullable=True, comment='用户状态 1、激活 2、未激活 3、禁用'),
    sa.Column('remark', sa.String(length=2000), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户基本信息表',
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
