"""empty message

Revision ID: 8a2ed7930152
Revises: 2cded93def0c
Create Date: 2020-09-09 17:31:46.273010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2ed7930152'
down_revision = '2cded93def0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_commodity', 'user_information', ['userID'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_commodity', type_='foreignkey')
    # ### end Alembic commands ###
