"""empty message

Revision ID: abfabf7211c7
Revises: f66d8c02c2c6
Create Date: 2020-09-05 17:55:43.608535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abfabf7211c7'
down_revision = 'f66d8c02c2c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=2000), nullable=True))
    op.add_column('user', sa.Column('remark', sa.String(length=2000), nullable=True))
    op.drop_column('user', 'xm')
    op.drop_column('user', 'bz')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bz', mysql.VARCHAR(length=2000), nullable=True))
    op.add_column('user', sa.Column('xm', mysql.VARCHAR(length=2000), nullable=True))
    op.drop_column('user', 'remark')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
