"""empty message

Revision ID: f66d8c02c2c6
Revises: 
Create Date: 2020-09-05 17:42:45.034546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66d8c02c2c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=2000), nullable=False),
    sa.Column('xm', sa.String(length=2000), nullable=True),
    sa.Column('birth', sa.String(length=2000), nullable=True),
    sa.Column('telephone', sa.String(length=2000), nullable=True),
    sa.Column('email', sa.String(length=2000), nullable=True),
    sa.Column('password_hash', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=2000), nullable=True),
    sa.Column('bz', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
